pipeline {
  agent none
  stages {
    stage('Machine-version') {
      agent {
        docker { image 'ubuntu:latest' }
      }
      steps {
        sh ' echo "next stage is on the way"'
      }
    }
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    
  }
}
